-- =============================================
-- Services Catalog: Table, RLS policies, indexes, seed
-- Paste this into Supabase SQL Editor and run
-- Idempotent: safe to re-run
-- =============================================

-- 1) TABLE
CREATE TABLE IF NOT EXISTS public.services_catalog (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" text NOT NULL,
  icon text NOT NULL,
  "desc" text,
  "desc2" text,
  image_key text,         -- clave para mapear a assets locales o CDN
  image_url text,         -- opcional: URL remota si usas CDN
  is_active boolean DEFAULT true,
  sort_order int DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

COMMENT ON TABLE public.services_catalog IS 'Catálogo de servicios mostrados en la app';
COMMENT ON COLUMN public.services_catalog.image_key IS 'Clave del asset local (e.g., wheel-flat)';

-- Unicidad por type para poder hacer upserts
CREATE UNIQUE INDEX IF NOT EXISTS uq_services_type ON public.services_catalog("type");
CREATE INDEX IF NOT EXISTS idx_services_active ON public.services_catalog(is_active);
CREATE INDEX IF NOT EXISTS idx_services_sort ON public.services_catalog(sort_order);

-- 2) RLS + POLICIES
ALTER TABLE public.services_catalog ENABLE ROW LEVEL SECURITY;

-- Limpieza de políticas previas
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='services_catalog' AND policyname='Anyone can read services') THEN
    EXECUTE 'DROP POLICY "Anyone can read services" ON public.services_catalog';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='services_catalog' AND policyname='Admins and mechanics can manage services') THEN
    EXECUTE 'DROP POLICY "Admins and mechanics can manage services" ON public.services_catalog';
  END IF;
END $$;

-- SELECT: permitir lectura a todos (incluye anon)
CREATE POLICY "Anyone can read services"
  ON public.services_catalog FOR SELECT
  USING (true);

-- INSERT/UPDATE/DELETE: solo admin/mecánico
CREATE POLICY "Admins and mechanics can manage services"
  ON public.services_catalog FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.rol IN ('admin','mecanico')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.rol IN ('admin','mecanico')
    )
  );

-- 3) REALTIME (opcional)
ALTER PUBLICATION supabase_realtime ADD TABLE public.services_catalog;

-- 4) SEED (Upserts para los 6 servicios)
-- Nota: "engine-dmaged" coincide con el nombre del asset actual
INSERT INTO public.services_catalog ("type", icon, "desc", "desc2", image_key, is_active, sort_order)
VALUES
  (
    'Cambio de Llanta',
    'build',
    'Cambio o reparación de llantas',
    '¿Tu llanta decidió ''tomar una siesta'' en medio del camino? A veces el asfalto muerde, pero no te preocupes, nosotros traemos la curita (y el gato hidráulico).',
    'wheel-flat',
    true,
    10
  ),
  (
    'Batería Descargada',
    'battery-alert',
    'Auxilio con batería',
    '¿Tu batería se declaró en huelga de brazos caídos? Dale, que todos tenemos días de ''baja energía''. Nosotros llegamos con los cables mágicos para revivirla como en las películas. ¡Frankenstein estaría orgulloso!',
    'electric-damage',
    true,
    20
  ),
  (
    'Falta de Gasolina',
    'local-gas-station',
    'Servicio de gasolina',
    '¿El tanque decidió hacer dieta sin avisarte? Tranquilo, hasta los mejores olvidan parar en la gasolinera. Te llevamos combustible para que tu auto deje de hacerse el dramático.',
    'without-gasoline',
    true,
    30
  ),
  (
    'Remolque',
    'local-shipping',
    'Servicio de grúa',
    '¿Tu auto dijo ''hoy no me levanto de la cama''? A veces necesitan un taxi VIP. Nuestra grúa lo llevará con todo el glamour que merece, como una estrella de cine en su limusina.',
    'grua',
    true,
    40
  ),
  (
    'Revisión General',
    'search',
    'Diagnóstico del vehículo',
    '¿Tu auto suena como orquesta desafinada? Ruidos, vibraciones, lucecitas misteriosas... Somos los detectives de motores. CSI Automotriz a tu servicio.',
    'engine-dmaged',
    true,
    50
  ),
  (
    'Otro',
    'help-outline',
    'Otro tipo de servicio',
    '¿Tu problema es tan único que ni Google lo entiende? ¡Nos encantan los retos! Cuéntanos qué locura le pasó a tu auto y lo resolveremos juntos. Nada nos asusta... bueno, casi nada.',
    'not-idea-error',
    true,
    60
  )
ON CONFLICT ("type") DO UPDATE SET
  icon = EXCLUDED.icon,
  "desc" = EXCLUDED."desc",
  "desc2" = EXCLUDED."desc2",
  image_key = EXCLUDED.image_key,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();

-- 5) OPCIONAL: consulta rápida
-- SELECT type, icon, image_key FROM public.services_catalog ORDER BY sort_order;
